//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Details
    {
<<<<<<< HEAD
        public int Id_Provider_Details { get; set; }
        public int quantity_items { get; set; }
        public System.DateTime providing_date { get; set; }
        public int employee_id { get; set; }
        public int provided_products_id { get; set; }
        public int provider_name_id { get; set; }
        public string note { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual Provided_Products Provided_Products { get; set; }
=======
        public int Id { get; set; }
        public string quantity_items { get; set; }
        public System.DateTime providing_date { get; set; }
        public int provided_product_id { get; set; }
        public int provider_name_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual Provided_Product Provided_Product { get; set; }
>>>>>>> 63b9e90125f6ee582eaed2bb8e5b3086c386b453
        public virtual Provider_Name Provider_Name { get; set; }
    }
}
