//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Name
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider_Name()
        {
            this.Provider_Details = new HashSet<Provider_Details>();
        }
    
<<<<<<< HEAD
        public int Id_Provider_Name { get; set; }
        public string provider_name1 { get; set; }
=======
        public int Id { get; set; }
        public string name { get; set; }
>>>>>>> 63b9e90125f6ee582eaed2bb8e5b3086c386b453
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider_Details> Provider_Details { get; set; }
    }
}
